"""add fields

Revision ID: 0ad193d94393
Revises: 8a6626473d92
Create Date: 2023-12-09 17:46:03.422509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad193d94393'
down_revision: Union[str, None] = '8a6626473d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_urls', sa.Column('params', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_urls', 'params')
    # ### end Alembic commands ###