"""add transform

Revision ID: 5234890086c5
Revises: eea5a6a88188
Create Date: 2023-10-20 16:37:09.642996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5234890086c5'
down_revision: Union[str, None] = 'eea5a6a88188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_urls', sa.Column('file_url', sa.String(), nullable=False))
    op.add_column('photo_urls', sa.Column('qr_url', sa.String(length=255), nullable=True))
    op.drop_constraint('photo_urls_url_key', 'photo_urls', type_='unique')
    op.create_unique_constraint(None, 'photo_urls', ['file_url'])
    op.create_unique_constraint(None, 'photo_urls', ['qr_url'])
    op.drop_column('photo_urls', 'url')
    op.add_column('photos', sa.Column('qr_url', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'photos', ['qr_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='unique')
    op.drop_column('photos', 'qr_url')
    op.add_column('photo_urls', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'photo_urls', type_='unique')
    op.drop_constraint(None, 'photo_urls', type_='unique')
    op.create_unique_constraint('photo_urls_url_key', 'photo_urls', ['url'])
    op.drop_column('photo_urls', 'qr_url')
    op.drop_column('photo_urls', 'file_url')
    # ### end Alembic commands ###